'use client';

import React, { useState, useEffect } from "react";
import axios from "axios";
import { useRouter } from "next/navigation";
import Toast from "../../Components/UI/Toast";
import { FaWandMagicSparkles, FaFloppyDisk, FaPlus, FaTrash, FaXmark } from "react-icons/fa6";

export default function AICourseGenerator() {
  const router = useRouter();
  const [courseTitle, setCourseTitle] = useState("");
  const [categories, setCategories] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // Generated Course JSON state for editing
  const [generatedCourse, setGeneratedCourse] = useState(null);
  const [isPreviewModalOpen, setIsPreviewModalOpen] = useState(false);
  
  const [toast, setToast] = useState({ visible: false, message: "", type: "success" });

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const res = await axios.get("/api/categories", { withCredentials: true });
        const list = res.data?.categories || res.data || [];
        setCategories(list);
        if (list.length > 0) setSelectedCategory(list[0]._id);
      } catch (err) {
        console.error("Failed to load categories:", err);
      }
    };
    fetchCategories();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!courseTitle.trim()) {
      setToast({ visible: true, message: "Please enter a course title", type: "error" });
      return;
    }

    setIsGenerating(true);
    try {
      const response = await axios.post(
        "/api/ai/generate-course",
        { title: courseTitle.trim(), categoryId: selectedCategory },
        { withCredentials: true }
      );

      if (response.data?.success) {
        setGeneratedCourse(response.data.data);
        setIsPreviewModalOpen(true);
        setToast({ visible: true, message: "✨ Course generated by Gemini AI! Review and edit below.", type: "success" });
      }
    } catch (error) {
      console.error("Error generating course:", error);
      setToast({
        visible: true,
        message: error.response?.data?.message || "Failed to generate course with AI",
        type: "error",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveCourse = async () => {
    if (!generatedCourse || !generatedCourse.name) return;
    setIsSaving(true);
    try {
      const response = await axios.post("/api/ai/save-course", generatedCourse, {
        withCredentials: true,
      });

      if (response.data?.success) {
        setToast({ visible: true, message: "🎉 Course saved to database successfully!", type: "success" });
        setIsPreviewModalOpen(false);
        setGeneratedCourse(null);
        setCourseTitle("");
        setTimeout(() => router.push("/admin/courses"), 1500);
      }
    } catch (error) {
      console.error("Error saving course:", error);
      setToast({
        visible: true,
        message: error.response?.data?.message || "Failed to save course",
        type: "error",
      });
    } finally {
      setIsSaving(false);
    }
  };

  // Helper handlers to edit generated course fields in real time
  const updateCourseField = (field, value) => {
    setGeneratedCourse((prev) => ({ ...prev, [field]: value }));
  };

  const handleFeatureChange = (index, value) => {
    const updated = [...generatedCourse.features];
    updated[index] = value;
    setGeneratedCourse((prev) => ({ ...prev, features: updated }));
  };

  const addFeature = () => {
    setGeneratedCourse((prev) => ({
      ...prev,
      features: [...(prev.features || []), "New Course Feature"],
    }));
  };

  const removeFeature = (index) => {
    setGeneratedCourse((prev) => ({
      ...prev,
      features: prev.features.filter((_, i) => i !== index),
    }));
  };

  const handleModuleChange = (index, field, value) => {
    const updated = [...generatedCourse.modules];
    updated[index] = { ...updated[index], [field]: value };
    setGeneratedCourse((prev) => ({ ...prev, modules: updated }));
  };

  const addModule = () => {
    setGeneratedCourse((prev) => ({
      ...prev,
      modules: [...(prev.modules || []), { icon: "📌", title: "New Module Title" }],
    }));
  };

  const removeModule = (index) => {
    setGeneratedCourse((prev) => ({
      ...prev,
      modules: prev.modules.filter((_, i) => i !== index),
    }));
  };

  return (
    <div className="min-h-screen text-white p-6 md:p-10" style={{ background: "#080808" }}>
      {toast.visible && (
        <Toast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast({ visible: false, message: "", type: "success" })}
        />
      )}

      {/* Header */}
      <div className="max-w-5xl mx-auto mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-orange-400 mb-1">
            <FaWandMagicSparkles /> AI Automation Studio
          </div>
          <h1 className="text-3xl md:text-4xl font-black">AI Course Generator</h1>
          <p className="text-gray-400 text-sm mt-1">
            Enter a course title. Gemini AI will generate the full curriculum, features, details & SEO matching your DB schema.
          </p>
        </div>
      </div>

      {/* Main Form */}
      <div className="max-w-5xl mx-auto bg-surface p-8 rounded-2xl border border-default shadow-xl mb-10">
        <form onSubmit={handleGenerate} className="space-y-6">
          <div>
            <label className="block text-sm font-bold text-gray-300 mb-2">
              Course Title / Name <span className="text-orange-500">*</span>
            </label>
            <input
              type="text"
              required
              value={courseTitle}
              onChange={(e) => setCourseTitle(e.target.value)}
              placeholder="e.g. Master React 19 & Next.js 16 Fullstack Development"
              className="w-full px-5 py-4 bg-black/40 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-orange-500 transition"
            />
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-300 mb-2">Course Category</label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-full px-5 py-4 bg-black/40 border border-white/10 rounded-xl text-white focus:outline-none focus:border-orange-500 transition"
            >
              {categories.map((cat) => (
                <option key={cat._id} value={cat._id} className="bg-neutral-900 text-white">
                  {cat.name}
                </option>
              ))}
            </select>
          </div>

          <button
            type="submit"
            disabled={isGenerating}
            className="w-full py-4 bg-gradient-to-r from-orange-500 to-amber-500 text-white font-bold rounded-xl shadow-lg hover:from-orange-600 hover:to-amber-600 transition duration-200 flex items-center justify-center gap-3 disabled:opacity-50 cursor-pointer"
          >
            {isGenerating ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-b-2 border-white" />
                Generating Complete Course with Gemini AI...
              </>
            ) : (
              <>
                <FaWandMagicSparkles /> Generate Course with Gemini AI
              </>
            )}
          </button>
        </form>
      </div>

      {/* Editable Preview Modal / Container */}
      {isPreviewModalOpen && generatedCourse && (
        <div className="max-w-5xl mx-auto bg-surface border border-orange-500/40 p-8 rounded-2xl shadow-2xl animate-fadeIn relative">
          <div className="flex items-center justify-between pb-6 border-b border-white/10 mb-6">
            <div className="flex items-center gap-3">
              <span className="p-3 bg-orange-500/20 text-orange-400 rounded-xl text-xl">
                <FaWandMagicSparkles />
              </span>
              <div>
                <h2 className="text-2xl font-bold">Review & Edit Generated Course</h2>
                <p className="text-xs text-gray-400">Tweak any fields below before saving to Database</p>
              </div>
            </div>
            <button
              onClick={() => setIsPreviewModalOpen(false)}
              className="text-gray-400 hover:text-white text-xl p-2"
            >
              <FaXmark />
            </button>
          </div>

          <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-2 custom-scrollbar">
            {/* Title & Price */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="md:col-span-2">
                <label className="block text-xs font-bold text-gray-400 mb-1">Course Name</label>
                <input
                  type="text"
                  value={generatedCourse.name || ""}
                  onChange={(e) => updateCourseField("name", e.target.value)}
                  className="w-full px-4 py-3 bg-black/40 border border-white/10 rounded-lg text-white font-semibold text-sm"
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-gray-400 mb-1">Price (₹)</label>
                <input
                  type="number"
                  value={generatedCourse.price || 0}
                  onChange={(e) => updateCourseField("price", Number(e.target.value))}
                  className="w-full px-4 py-3 bg-black/40 border border-white/10 rounded-lg text-white font-semibold text-sm"
                />
              </div>
            </div>

            {/* Description */}
            <div>
              <label className="block text-xs font-bold text-gray-400 mb-1">Description</label>
              <textarea
                rows={4}
                value={generatedCourse.description || ""}
                onChange={(e) => updateCourseField("description", e.target.value)}
                className="w-full px-4 py-3 bg-black/40 border border-white/10 rounded-lg text-white text-sm"
              />
            </div>

            {/* Features */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-bold text-gray-400 uppercase tracking-wider">
                  Key Features ({generatedCourse.features?.length || 0})
                </label>
                <button
                  type="button"
                  onClick={addFeature}
                  className="text-xs text-orange-400 font-bold flex items-center gap-1 hover:underline"
                >
                  <FaPlus /> Add Feature
                </button>
              </div>
              <div className="space-y-2">
                {generatedCourse.features?.map((feat, idx) => (
                  <div key={idx} className="flex items-center gap-2">
                    <input
                      type="text"
                      value={feat}
                      onChange={(e) => handleFeatureChange(idx, e.target.value)}
                      className="flex-1 px-4 py-2.5 bg-black/40 border border-white/10 rounded-lg text-sm text-gray-200"
                    />
                    <button
                      type="button"
                      onClick={() => removeFeature(idx)}
                      className="text-red-400 hover:text-red-300 p-2.5"
                    >
                      <FaTrash />
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Modules */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-bold text-gray-400 uppercase tracking-wider">
                  Modules ({generatedCourse.modules?.length || 0})
                </label>
                <button
                  type="button"
                  onClick={addModule}
                  className="text-xs text-orange-400 font-bold flex items-center gap-1 hover:underline"
                >
                  <FaPlus /> Add Module
                </button>
              </div>
              <div className="space-y-3">
                {generatedCourse.modules?.map((mod, idx) => (
                  <div key={idx} className="flex items-center gap-2 p-3 bg-black/30 border border-white/5 rounded-xl">
                    <input
                      type="text"
                      value={mod.icon || "🚀"}
                      onChange={(e) => handleModuleChange(idx, "icon", e.target.value)}
                      className="w-12 text-center py-2 bg-black/50 border border-white/10 rounded-lg text-sm"
                    />
                    <input
                      type="text"
                      value={mod.title || ""}
                      onChange={(e) => handleModuleChange(idx, "title", e.target.value)}
                      className="flex-1 px-4 py-2 bg-black/50 border border-white/10 rounded-lg text-sm text-white"
                    />
                    <button
                      type="button"
                      onClick={() => removeModule(idx)}
                      className="text-red-400 hover:text-red-300 p-2"
                    >
                      <FaTrash />
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* SEO Metadata */}
            <div className="p-4 bg-black/30 rounded-xl border border-white/5 space-y-3">
              <h4 className="text-xs font-bold text-orange-400 uppercase tracking-wider">SEO Metadata</h4>
              <div>
                <label className="block text-xs text-gray-400 mb-1">Meta Title</label>
                <input
                  type="text"
                  value={generatedCourse.seo?.metaTitle || ""}
                  onChange={(e) =>
                    setGeneratedCourse((prev) => ({
                      ...prev,
                      seo: { ...prev.seo, metaTitle: e.target.value },
                    }))
                  }
                  className="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-lg text-xs text-gray-200"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-400 mb-1">Meta Description</label>
                <input
                  type="text"
                  value={generatedCourse.seo?.metaDescription || ""}
                  onChange={(e) =>
                    setGeneratedCourse((prev) => ({
                      ...prev,
                      seo: { ...prev.seo, metaDescription: e.target.value },
                    }))
                  }
                  className="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-lg text-xs text-gray-200"
                />
              </div>
            </div>
          </div>

          {/* Modal Actions */}
          <div className="pt-6 border-t border-white/10 flex items-center justify-end gap-4 mt-6">
            <button
              onClick={() => setIsPreviewModalOpen(false)}
              className="px-6 py-3 bg-white/10 hover:bg-white/15 text-white font-semibold rounded-xl text-sm transition"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveCourse}
              disabled={isSaving}
              className="px-8 py-3 bg-orange-500 hover:bg-orange-600 text-white font-bold rounded-xl text-sm transition flex items-center gap-2 shadow-lg cursor-pointer"
            >
              {isSaving ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent" />
                  Saving to DB...
                </>
              ) : (
                <>
                  <FaFloppyDisk /> Save Course to Database
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
